### ISSUE TITLE
$$hashKey is saved in SwellRT

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/angular-swellrt#24]
In some way, cbcd1c0e26764931ead817c1074f6e6dd62a7aea introduced a bug related with $$hashKey. This param should be ignored in order to not to be saved in SwellRT. This is the SwellRT trace:

```
java.lang.IllegalArgumentException: fields stored in the db can't start with '$' (Bad Key: '$$hashKey')
at com.mongodb.DBCollection.validateKey(DBCollection.java:1450)
at com.mongodb.DBCollection._checkKeys(DBCollection.java:1410)
at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
at com.mongodb.DBCollection._checkObject(DBCollection.java:1397)
at com.mongodb.DBApiLayer$MyCollection.update(DBApiLayer.java:318)
at com.mongodb.DBCollection.update(DBCollection.java:178)
at com.mongodb.DBCollection.update(DBCollection.java:209)
at org.swellrt.server.box.index.ModelIndexerDispatcherImpl.storeDataM
```

**Comment by atfornes** [comment]
I messed up with the words haskKey, hashKey, huskie...
![index](https://cloud.githubusercontent.com/assets/7475584/17138296/e2e73774-533f-11e6-90c7-761a955235b7.jpeg)

**Comment by pablojan** [comment]
Cool!

2016-07-26 14:47 GMT+02:00 atfornes notifications@github.com:
